name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "New features"
    labels: ["feature", "enhancement"]
  - title: "Bug fixes"
    labels: ["bug", "fix"]
  - title: "Maintenance"
    labels: ["chore", "dependencies", "ci"]
  - title: "Documentation"
    labels: ["documentation"]

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels: ["breaking-change"]
  minor:
    labels: ["feature", "enhancement"]
  patch:
    labels: ["bug", "fix", "chore", "dependencies", "ci", "documentation"]
  default: patch

template: |
  ## What's changed

  $CHANGES

  **Full changelog:** https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
